packages:
- logtape
- adaptor-pino
- adaptor-winston
- adaptor-log4js
- file
- otel
- pretty
- redaction
- sentry
- syslog
- cloudwatch-logs
- windows-eventlog
- docs
- benchmarks

catalog:
  "@alinea/suite": ^0.6.3
  "@david/which-runtime": jsr:^0.2.1
  "@std/assert": jsr:^1.0.13
  "@std/async": jsr:^1.0.13
  "@std/dotenv": jsr:^0.225.5
  "@std/path": jsr:^1.1.0
  consolemock: ^1.1.0
  tsdown: ^0.12.7
  typescript: ^5.8.3

ignoredBuiltDependencies:
- koffi
